### PR TITLE
🔀 :: (#63) login animation

### PR DESCRIPTION
**Pull request by 100Seung-Min**

### CODE REVIEW

**Review by sihun96 — APPROVED** [review]
냐미~

**Review by kimsh153 — APPROVED** [review]

**Review by louis7308 — APPROVED** [review]
LGTM 굿

**Review by baekteun — APPROVED** [review]
LGTM

**Review by sagwamatrlawns — APPROVED** [review]
LGTM

**Review by khs3994 — APPROVED** [review]
LGTM

**Comment by HumanIearning** [comment]
satisfying

**Pull request merged**
